version: '3.7'

services:
  postgres:
    image: hammermc/nominatim-docker
    restart: always
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    env_file:
      - osm.env
    volumes:
      - data:/data
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - run:/run
    tmpfs:
      - /tmp

  initdb:
    image: hammermc/nominatim-docker
    restart: on-failure
    depends_on:
      - postgres
    command: nominatim-initdb
    env_file:
      - osm.env
    environment:
      - REDOWNLOAD
      - REINITDB
    volumes:
      - data:/data
      - run:/run
      - ./osm-config.sh:/usr/local/etc/osm-config.sh
      - ./apache/local.php:/Nominatim/build/settings/local.php
    tmpfs:
      - /tmp

#  edit apache/local.php for correct update settings
  update:
    image: hammermc/nominatim-docker
    restart: unless-stopped
    depends_on:
      - postgres
    command: nominatim-updatedb
    env_file:
      - osm.env
    environment:
      - REDOWNLOAD
      - REINITDB
    volumes:
      - data:/data
      - run:/run
      - ./osm-config.sh:/usr/local/etc/osm-config.sh
      - ./apache/local.php:/Nominatim/build/settings/local.php
    tmpfs:
      - /tmp

  apache:
    image: hammermc/nominatim-docker
    restart: always
    depends_on:
      - initdb
    env_file:
      - osm.env
    command: nominatim-apache2
    volumes:
      - data:/data
      - run:/run
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache/local.php:/Nominatim/build/settings/local.php
      - ./osm-config.sh:/usr/local/etc/osm-config.sh
    tmpfs:
      - /tmp
    ports:
      - 80:80


volumes:
  data:
  postgres-data:
  run:
